# Generated by Django 4.0.5 on 2022-06-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_remove_post_likes_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
