# Generated by Django 4.0.5 on 2022-06-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0004_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
